import type {
  User,
  Post,
  Conversation,
  Message,
  TrendingTopic,
  TrendingPost,
  TrendingCreator,
  TrendingRealm,
} from "@/components/types"

// Current user (logged in)
export const currentUser: User = {
  id: "current-user",
  name: "Alex Chen",
  username: "alexchen",
  email: "alex@example.com",
  userRole: "creator",
  workerRole: "admin",
  level: 28,
  xp: 9800,
  influenceScore: 520,
  followers: 1250,
  following: 342,
  bio: "Passionate creator, developer, and community builder. Always learning and sharing insights.",
  joinedDate: "January 2023",
  location: "San Francisco, CA",
  badges: [
    { id: "b1", name: "Rising Star", icon: "⭐", rarity: "rare" },
    { id: "b2", name: "Trusted", icon: "✓", rarity: "common" },
    { id: "b3", name: "Influencer", icon: "👑", rarity: "epic" },
  ],
  achievements: [
    {
      id: "a1",
      name: "First Post",
      icon: "📝",
      description: "Published your first post.",
      rarity: "common",
      unlockedAt: new Date("2023-01-01"),
    },
    {
      id: "a2",
      name: "1000 Followers",
      icon: "👥",
      description: "Reached 1000 followers.",
      rarity: "epic",
      unlockedAt: new Date("2023-02-01"),
    },
  ],
  avatar: "/professional-man-avatar.png",
  bannerImage: "/abstract-tech-banner.png",
  realm: "Code Realm",
  isOnline: true,
}

// All users in the system
export const allUsers: User[] = [
  currentUser,
  {
    id: "u2",
    name: "Sarah Wolf",
    username: "sarahwolf",
    userRole: "analyst",
    workerRole: "mod",
    level: 35,
    xp: 15200,
    influenceScore: 890,
    followers: 2100,
    following: 450,
    bio: "Data enthusiast and community moderator. Helping others grow.",
    joinedDate: "December 2022",
    location: "New York, NY",
    badges: [{ id: "b1", name: "Master Analyst", icon: "📊", rarity: "legendary" }],
    achievements: [
      {
        id: "a3",
        name: "Data Analysis Expert",
        icon: "📊",
        description: "Completed advanced data analysis course.",
        rarity: "legendary",
        unlockedAt: new Date("2023-03-01"),
      },
    ],
    avatar: "/professional-woman-avatar.png",
    bannerImage: "/data-visualization-banner.jpg",
    realm: "Data Realm",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "u3",
    name: "Marcus Echo",
    username: "marcusecho",
    userRole: "entertainer",
    workerRole: undefined,
    level: 32,
    xp: 12500,
    influenceScore: 750,
    followers: 1800,
    following: 600,
    bio: "Content creator, entertainer, always bringing the fun!",
    joinedDate: "March 2023",
    location: "Los Angeles, CA",
    badges: [],
    avatar: "/creative-man-avatar.jpg",
    bannerImage: "/entertainment-banner.jpg",
    realm: "Entertainment Hub",
    isOnline: false,
    lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "u4",
    name: "Emma Rodriguez",
    username: "emmarodriguez",
    userRole: "educator",
    workerRole: "developer",
    level: 42,
    xp: 22300,
    influenceScore: 1200,
    followers: 3500,
    following: 280,
    bio: "Educator passionate about teaching web development and coding.",
    joinedDate: "August 2022",
    location: "Austin, TX",
    badges: [
      { id: "b1", name: "Top Educator", icon: "🎓", rarity: "epic" },
      { id: "b2", name: "Verified", icon: "✔", rarity: "legendary" },
    ],
    achievements: [
      {
        id: "a5",
        name: "Web Dev Master",
        icon: "💻",
        description: "Completed web development masterclass.",
        rarity: "legendary",
        unlockedAt: new Date("2023-05-01"),
      },
    ],
    avatar: "/educator-woman-avatar.jpg",
    bannerImage: "/coding-education-banner.jpg",
    realm: "Learning Hub",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "u5",
    name: "James Park",
    username: "jamespark",
    userRole: "explorer",
    workerRole: "support",
    level: 22,
    xp: 6700,
    influenceScore: 380,
    followers: 890,
    following: 1200,
    bio: "Exploring new tech, sharing discoveries, and helping newcomers.",
    joinedDate: "June 2023",
    location: "Seattle, WA",
    badges: [{ id: "b1", name: "Helper", icon: "🤝", rarity: "common" }],
    avatar: "/tech-explorer-man-avatar.jpg",
    bannerImage: "/technology-exploration-banner.jpg",
    realm: "Discovery Zone",
    isOnline: false,
    lastSeen: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]

// User posts map
export const userPostsMap: Record<string, Post[]> = {
  "current-user": [
    {
      id: "p1",
      author: allUsers[0],
      title: "Building Next.js 15 Apps",
      description: "Exploring the latest features in Next.js 15 and how to leverage them for better performance.",
      image: "/nextjs-development.png",
      likes: 234,
      comments: 45,
      shares: 23,
      views: 1500,
      tags: ["nextjs", "webdev", "tutorial"],
      rarity: "rare",
      rating: 4.8,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: "p1b",
      author: allUsers[0],
      title: "React Server Components Deep Dive",
      description: "Understanding how RSC works under the hood and when to use them.",
      image: "/react-components.png",
      likes: 456,
      comments: 78,
      shares: 45,
      views: 2300,
      tags: ["react", "rsc", "performance"],
      rarity: "epic",
      rating: 4.9,
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
  ],
  u2: [
    {
      id: "p2",
      author: allUsers[1],
      title: "Data Analysis Best Practices",
      description: "Learn how to structure your data analysis workflow effectively.",
      image: "/data-analysis-charts.png",
      likes: 567,
      comments: 89,
      shares: 67,
      views: 3200,
      tags: ["data", "analysis", "tutorial"],
      rarity: "epic",
      rating: 4.9,
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
  ],
  u3: [
    {
      id: "p3",
      author: allUsers[2],
      title: "Fun with Content Creation",
      description: "Tips and tricks for creating engaging entertainment content.",
      image: "/content-creation-studio.jpg",
      likes: 892,
      comments: 156,
      shares: 234,
      views: 5600,
      tags: ["content", "entertainment", "tips"],
      rarity: "rare",
      rating: 4.5,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
  ],
  u4: [
    {
      id: "p4",
      author: allUsers[3],
      title: "Web Development Masterclass",
      description: "Complete guide to modern web development with React and Next.js.",
      image: "/web-development-coding.png",
      likes: 1234,
      comments: 345,
      shares: 456,
      views: 8900,
      tags: ["webdev", "education", "masterclass"],
      rarity: "epic",
      rating: 4.95,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
  ],
  u5: [
    {
      id: "p5",
      author: allUsers[4],
      title: "Discovering New Technologies",
      description: "Join me as I explore the latest and greatest in tech.",
      image: "/technology-innovation.jpg",
      likes: 456,
      comments: 78,
      shares: 34,
      views: 2100,
      tags: ["tech", "discovery", "news"],
      rarity: "rare",
      rating: 4.3,
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
  ],
}

// Mock conversations
export const mockConversations: Conversation[] = [
  {
    id: "c1",
    user1: currentUser,
    user2: allUsers[1],
    lastMessage: {
      id: "m1",
      sender: allUsers[1],
      receiver: currentUser,
      content: "Hey! How's the project going?",
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      read: false,
      status: "delivered",
    },
    unreadCount: 2,
    lastUpdated: new Date(Date.now() - 5 * 60 * 1000),
    isPinned: true,
  },
  {
    id: "c2",
    user1: currentUser,
    user2: allUsers[2],
    lastMessage: {
      id: "m2",
      sender: currentUser,
      receiver: allUsers[2],
      content: "Thanks for the update!",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    unreadCount: 0,
    lastUpdated: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "c3",
    user1: currentUser,
    user2: allUsers[3],
    lastMessage: {
      id: "m3",
      sender: allUsers[3],
      receiver: currentUser,
      content: "Looking forward to our collaboration!",
      timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    unreadCount: 0,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "c4",
    user1: currentUser,
    user2: allUsers[4],
    lastMessage: {
      id: "m4",
      sender: allUsers[4],
      receiver: currentUser,
      content: "Check out this new framework I found!",
      timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    unreadCount: 0,
    lastUpdated: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isArchived: true,
  },
]

// Mock messages for each conversation
export const mockMessages: Record<string, Message[]> = {
  c1: [
    {
      id: "m1a",
      sender: currentUser,
      receiver: allUsers[1],
      content: "Hey Sarah! How are you?",
      timestamp: new Date(Date.now() - 30 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m1b",
      sender: allUsers[1],
      receiver: currentUser,
      content: "Doing great! Just finished analyzing the Q4 data. The results are impressive!",
      timestamp: new Date(Date.now() - 28 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m1c",
      sender: currentUser,
      receiver: allUsers[1],
      content: "That sounds amazing! Can you share the highlights?",
      timestamp: new Date(Date.now() - 25 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m1d",
      sender: allUsers[1],
      receiver: currentUser,
      content: "User engagement is up 45% and retention improved by 23%",
      timestamp: new Date(Date.now() - 20 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m1e",
      sender: allUsers[1],
      receiver: currentUser,
      content: "Hey! How's the project going?",
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      read: false,
      status: "delivered",
    },
  ],
  c2: [
    {
      id: "m2a",
      sender: currentUser,
      receiver: allUsers[2],
      content: "Hey Marcus! Check out my latest content",
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m2b",
      sender: allUsers[2],
      receiver: currentUser,
      content: "Will do! Sounds exciting. I'll check it out tonight",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m2c",
      sender: currentUser,
      receiver: allUsers[2],
      content: "Thanks for the update!",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
  ],
  c3: [
    {
      id: "m3a",
      sender: currentUser,
      receiver: allUsers[3],
      content: "Hi Emma! Interested in collaborating on a tutorial series?",
      timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m3b",
      sender: allUsers[3],
      receiver: currentUser,
      content: "I'd love to work together. What topics were you thinking?",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m3c",
      sender: currentUser,
      receiver: allUsers[3],
      content: "Maybe something about React Server Components and modern patterns?",
      timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
    {
      id: "m3d",
      sender: allUsers[3],
      receiver: currentUser,
      content: "Looking forward to our collaboration!",
      timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
  ],
  c4: [
    {
      id: "m4a",
      sender: allUsers[4],
      receiver: currentUser,
      content: "Check out this new framework I found!",
      timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      read: true,
      status: "read",
    },
  ],
}

// Trending data
export const trendingTopics: TrendingTopic[] = [
  {
    id: "1",
    name: "Web Development",
    hashtag: "#WebDevelopment",
    posts: 45320,
    trend: "+28%",
    color: "from-blue-500 to-cyan-500",
    category: "Technology",
  },
  {
    id: "2",
    name: "AI & ML",
    hashtag: "#AI",
    posts: 38900,
    trend: "+42%",
    color: "from-purple-500 to-pink-500",
    category: "Technology",
  },
  {
    id: "3",
    name: "Design System",
    hashtag: "#DesignSystem",
    posts: 32450,
    trend: "+15%",
    color: "from-orange-500 to-red-500",
    category: "Design",
  },
  {
    id: "4",
    name: "Next.js",
    hashtag: "#NextJS",
    posts: 28900,
    trend: "+32%",
    color: "from-green-500 to-emerald-500",
    category: "Framework",
  },
  {
    id: "5",
    name: "TypeScript",
    hashtag: "#TypeScript",
    posts: 24500,
    trend: "+18%",
    color: "from-blue-600 to-blue-400",
    category: "Language",
  },
  {
    id: "6",
    name: "React 19",
    hashtag: "#React19",
    posts: 21300,
    trend: "+55%",
    color: "from-cyan-500 to-blue-500",
    category: "Framework",
  },
]

export const trendingPosts: TrendingPost[] = [
  {
    id: "1",
    title: "The Future of AI in Web Development",
    author: "Tech Guru",
    authorAvatar: "/tech-guru-avatar.png",
    likes: 2341,
    comments: 456,
    trending: 1,
    image: "/ai-web-development.jpg",
    tags: ["AI", "webdev", "future"],
  },
  {
    id: "2",
    title: "Building Scalable Systems with Microservices",
    author: "System Architect",
    authorAvatar: "/architect-avatar.png",
    likes: 1890,
    comments: 234,
    trending: 2,
    image: "/microservices-architecture.png",
    tags: ["architecture", "scalability", "microservices"],
  },
  {
    id: "3",
    title: "Design System Best Practices for 2024",
    author: "Design Lead",
    authorAvatar: "/diverse-designer-avatars.png",
    likes: 1567,
    comments: 189,
    trending: 3,
    image: "/design-system-components.png",
    tags: ["design", "ui", "components"],
  },
  {
    id: "4",
    title: "Mastering TypeScript Generics",
    author: "Code Master",
    authorAvatar: "/coder-avatar.png",
    likes: 1234,
    comments: 167,
    trending: 4,
    image: "/typescript-code.png",
    tags: ["typescript", "generics", "tutorial"],
  },
]

export const trendingCreators: TrendingCreator[] = [
  {
    id: "1",
    name: "Alex Chen",
    username: "alexchen",
    followers: 15420,
    role: "Creator",
    avatar: "/creator-alex.jpg",
    isVerified: true,
    growth: "+12%",
  },
  {
    id: "2",
    name: "Sarah Wolf",
    username: "sarahwolf",
    followers: 12890,
    role: "Analyst",
    avatar: "/analyst-sarah.jpg",
    isVerified: true,
    growth: "+8%",
  },
  {
    id: "3",
    name: "Marcus Echo",
    username: "marcusecho",
    followers: 9870,
    role: "Entertainer",
    avatar: "/entertainer-marcus.jpg",
    isVerified: false,
    growth: "+15%",
  },
  {
    id: "4",
    name: "Emma Rodriguez",
    username: "emmarodriguez",
    followers: 8540,
    role: "Educator",
    avatar: "/educator-emma.jpg",
    isVerified: true,
    growth: "+22%",
  },
  {
    id: "5",
    name: "James Park",
    username: "jamespark",
    followers: 6230,
    role: "Explorer",
    avatar: "/explorer-james.jpg",
    isVerified: false,
    growth: "+5%",
  },
]

export const trendingRealms: TrendingRealm[] = [
  {
    id: "1",
    name: "Code Realm",
    members: 45320,
    trend: "+12%",
    icon: "💻",
    description: "For developers and coders",
    category: "Technology",
  },
  {
    id: "2",
    name: "Design Hub",
    members: 38900,
    trend: "+24%",
    icon: "🎨",
    description: "Creative design community",
    category: "Design",
  },
  {
    id: "3",
    name: "Data Realm",
    members: 32450,
    trend: "+8%",
    icon: "📊",
    description: "Data science and analytics",
    category: "Analytics",
  },
  {
    id: "4",
    name: "Entertainment",
    members: 28900,
    trend: "+18%",
    icon: "🎬",
    description: "Content creators unite",
    category: "Media",
  },
  {
    id: "5",
    name: "Learning Hub",
    members: 24500,
    trend: "+32%",
    icon: "📚",
    description: "Education and tutorials",
    category: "Education",
  },
  {
    id: "6",
    name: "Discovery Zone",
    members: 18700,
    trend: "+10%",
    icon: "🔍",
    description: "Explore new technologies",
    category: "Exploration",
  },
]

// Helper function to get user by ID
export function getUserById(id: string): User | undefined {
  return allUsers.find((user) => user.id === id)
}

// Helper function to get posts by user ID
export function getPostsByUserId(userId: string): Post[] {
  return userPostsMap[userId] || []
}

// Helper function to format relative time
export function formatRelativeTime(date: Date): string {
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return "Just now"
  if (minutes < 60) return `${minutes}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`
  return date.toLocaleDateString()
}

// Helper function to format number with K/M suffix
export function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  return num.toString()
}

export const mockPosts: Post[] = [
  {
    id: "1",
    author: allUsers[0],
    title: "Building a 3D Code Visualization Tool",
    description:
      "Just finished my latest project - a 3D visualization tool for tracking and analyzing code complexity. Really proud of how it turned out!",
    image: "/3d-code-visualization-abstract-art.jpg",
    likes: 234,
    comments: 45,
    shares: 23,
    views: 1500,
    tags: ["ThreeJS", "React", "WebGL"],
    rarity: "epic",
    rating: 4,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "2",
    author: allUsers[1],
    title: "Deep Dive into Web Performance Optimization",
    description:
      "Sharing my learnings from optimizing a large-scale web application. Here are the key strategies that made the biggest impact...",
    image: "/web-performance-dashboard.png",
    likes: 567,
    comments: 89,
    shares: 67,
    views: 3200,
    tags: ["Performance", "Web", "Optimization"],
    rarity: "legendary",
    rating: 5,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: "3",
    author: allUsers[2],
    title: "My Latest Design System Project",
    description:
      "Excited to share my new design system I've been working on. It really streamlines our design process!",
    image: "/design-system-components-ui.jpg",
    likes: 892,
    comments: 156,
    shares: 234,
    views: 5600,
    tags: ["Design", "System", "UI"],
    rarity: "rare",
    rating: 4.5,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: "4",
    author: allUsers[3],
    title: "React Server Components Explained",
    description:
      "A comprehensive guide to understanding React Server Components and how they can improve your app's performance.",
    image: "/react-server-components-code.jpg",
    likes: 1234,
    comments: 234,
    shares: 156,
    views: 8900,
    tags: ["React", "RSC", "Performance"],
    rarity: "epic",
    rating: 4.8,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: "5",
    author: allUsers[4],
    title: "Exploring New AI Tools for Developers",
    description: "I've been testing various AI coding assistants and here are my honest thoughts on each one...",
    image: "/ai-developer-tools.jpg",
    likes: 456,
    comments: 78,
    shares: 45,
    views: 2100,
    tags: ["AI", "Tools", "Development"],
    rarity: "rare",
    rating: 4.2,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
]
